## Loss or Cost Function

#### Tensorflow loss value examples

* sparse_categorical_crossentropy
* binary_crossentropy
* categroical_crossentropy
* mean_absolute_error
* mean_squared_eeor

In [3]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30, 0.7, 1, 0 , 0.5])

## Mean Absolute Error

In [5]:
def mean_absolute_error(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += abs(yt - yp)
    print("Total error : ", total_error)
    mae = total_error / len(y_true)
    print("Mean Absolute Error : ", mae)

In [7]:
mean_absolute_error(y_true, y_predicted)

Total error :  2.5
Mean Absolute Error :  0.5


#### Implement same thing using numpy in much easier way

In [9]:
print(np.sum(np.abs(y_predicted - y_true)))
np.mean(np.abs(y_predicted - y_true))

2.5


0.5

In [29]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [31]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [33]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [35]:
mae_np(y_predicted, y_true)

0.5

## Log Loss or Binary Cross Entropy

In [11]:
np.log([0.000000000001])

array([-27.63102112])

In [13]:
epsilon = 1e-15

In [15]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [17]:
y_predicted_new = [min(i, 1- epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [19]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [21]:
-np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

17.2696280766844

In [23]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1 - epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

In [25]:
log_loss(y_true, y_predicted)

17.2696280766844